Update scraper.yml

diff --git a/.github/workflows/scraper.yml b/.github/workflows/scraper.yml
--- a/.github/workflows/scraper.yml
+++ b/.github/workflows/scraper.yml
@@ -2,6 +2,12 @@ name: First Scraper
 
 on:
   workflow_dispatch:
+    inputs:
+      state:
+        description: "U.S. state to scrape"
+        required: true
+        default: 'ia'
+        
   schedule:
   - cron: "0 0 * * *" # GMT/London;look at crontab.guru for schedule
 
@@ -14,7 +20,7 @@ jobs:
     runs-on: ubuntu-latest # blank computer, clone repo into your computer
     steps:  
       - name: Checkout  # uses a shortcut from marketplace unlike run from past action
-        uses: actions/checkout@v4                                 # packaged action//libraries in the open
+        uses: actions/checkout@v4                                  #packaged action//libraries in the open
 
       - name: Install Python                                       #step 2 for job called scrape
         uses: actions/setup-python@v5                              #prepacked action
@@ -26,7 +32,10 @@ jobs:
         run: pip install warn-scraper
         
       - name: Scrape
-        run: warn-scraper ia --data-dir ./data/                     # where to save warn data from Iowa
+        run: warn-scraper ${{ inputs.state }} --data-dir ./data/    # where to save warn data from Iowa
+
+      - name: Save datestamp                                        #add date to text file to ensure repo is action so that GH keeps runnning it
+        run: date > ./data/latest-scrape.txt
 
       # computer saves data and checks back in with you
       - name: Commit and push
@@ -34,4 +43,4 @@ jobs:
           git config user.name "GitHub Actions"
           git config user.email "actions@users.noreply.github.com"
           git add ./data/                                           # can change director
-          git commit -m "Latest data for Iowa" && git push || true  # if you have nothing to commit it wont fail      
+          git commit -m "Latest data for ${{ inputs.state }}" && git push || true  # if you have nothing to commit it wont fail      
